# Generated by Django 5.1.6 on 2025-03-25 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '1065_workflowaction_assign_custom_fields_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='correspondent',
            name='external_reference',
            field=models.TextField(blank=True, help_text='Reference to an external system, like customer ID, etc.', verbose_name='external reference'),
        ),
        migrations.AddField(
            model_name='correspondent',
            name='remark',
            field=models.TextField(blank=True, help_text='Note to this entry', verbose_name='remark'),
        ),
        migrations.AddField(
            model_name='customfield',
            name='remark',
            field=models.TextField(blank=True, help_text='Note to this entry', verbose_name='remark'),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='remark',
            field=models.TextField(blank=True, help_text='Note to this entry', verbose_name='remark'),
        ),
        migrations.AddField(
            model_name='storagepath',
            name='remark',
            field=models.TextField(blank=True, help_text='Note to this entry', verbose_name='remark'),
        ),
        migrations.AddField(
            model_name='tag',
            name='remark',
            field=models.TextField(blank=True, help_text='Note to this entry', verbose_name='remark'),
        ),
    ]
