# Generated by Django 5.1.8 on 2025-04-30 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '1066_correspondent_external_reference_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customfield',
            options={'ordering': ('order',), 'verbose_name': 'custom field', 'verbose_name_plural': 'custom fields'},
        ),
        migrations.AddField(
            model_name='customfield',
            name='group',
            field=models.TextField(blank=True, help_text='Name to group fields together', null=True, verbose_name='group'),
        ),
        migrations.AddField(
            model_name='customfield',
            name='hidden',
            field=models.BooleanField(default=False, help_text='Hide this field from the user interface', verbose_name='hidden'),
        ),
        migrations.AddField(
            model_name='customfield',
            name='label',
            field=models.TextField(blank=True, help_text='A user facing label', null=True, verbose_name='label'),
        ),
        migrations.AddField(
            model_name='customfield',
            name='order',
            field=models.IntegerField(default=0, verbose_name='order'),
        ),
        migrations.AddField(
            model_name='customfieldinstance',
            name='value_json',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='customfieldinstance',
            name='value_text_multiline',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='data_type',
            field=models.CharField(choices=[('string', 'String'), ('url', 'URL'), ('date', 'Date'), ('boolean', 'Boolean'), ('integer', 'Integer'), ('float', 'Float'), ('monetary', 'Monetary'), ('documentlink', 'Document Link'), ('select', 'Select'), ('json', 'JSON'), ('text', 'Text')], editable=False, max_length=50, verbose_name='data type'),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='remark',
            field=models.TextField(blank=True, help_text='Note to this entry', null=True, verbose_name='remark'),
        ),
    ]
