# Generated by Django 5.1.3 on 2025-03-24 17:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "1073_migrate_workflow_title_jinja"),
    ]

    operations = [
        migrations.AddField(
            model_name="correspondent",
            name="external_reference",
            field=models.TextField(
                blank=True,
                help_text="External reference to link to other systems",
                verbose_name="external reference",
            ),
        ),
        migrations.AddField(
            model_name="correspondent",
            name="remark",
            field=models.TextField(blank=True, verbose_name="remark"),
        ),
        migrations.AddField(
            model_name="customfield",
            name="remark",
            field=models.TextField(blank=True, verbose_name="remark"),
        ),
        migrations.AddField(
            model_name="documenttype",
            name="remark",
            field=models.TextField(blank=True, verbose_name="remark"),
        ),
        migrations.AddField(
            model_name="storagepath",
            name="remark",
            field=models.TextField(blank=True, verbose_name="remark"),
        ),
        migrations.AddField(
            model_name="tag",
            name="remark",
            field=models.TextField(blank=True, verbose_name="remark"),
        ),
    ]

