# Generated by Django 5.2.5 on 2025-10-20 16:59

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "1075_alter_customfield_options_customfield_group_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="customfieldinstance",
            name="documents_customfieldinstance_unique_document_field",
        ),
        migrations.AddIndex(
            model_name="customfieldinstance",
            index=models.Index(
                fields=["document", "field"],
                name="docs_cfi_doc_field_idx",
            ),
        ),
    ]

